# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
locale: en-US
title: Zi Lin
my_site_title: Zi Lin
#name: Zi Lin
description: "[firstname].[lastname]@pku.edu.cn"
baseurl: # the subpath of your site, e.g. "/blog"
#url: http://127.0.0.1:4000
url: https://zi-lin.github.io/ # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: /images/zilin.jpg # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Zi Lin
  picture:
  email: 
  twitter: zilin97
  facebook: zi.lin.12935
  github: zi-lin
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/zi-lin
    icon: fab fa-github-square
  - title: Facebook
    url: https://www.facebook.com/zi.lin.12935
    icon: fab fa-facebook-square
  - title: Twitter
    url: https://twitter.com/zilin97
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/linzi.pku
    icon: fab fa-instagram
  - title: Linkedin
    url: https://www.linkedin.com/in/zi-lin/
    icon: fab fa-linkedin